### ISSUE TITLE
Enable installation through pip and conda

### ISSUE THREAD

**Issue by lyrivera** [glotzerlab/garnett#101]

**Comment by bdice** [comment]
See signac for an example of automated deployment to PyPI. We may need to do some extra work to make it work for multiple architectures / multiple Python versions because it has Cython code.

https://github.com/glotzerlab/signac/blob/master/.circleci/config.yml
https://github.com/glotzerlab/signac/blob/master/.deploy.bash
https://github.com/glotzerlab/signac/blob/master/.test-deploy.bash

**Comment by lyrivera** [comment]
Resolved.
