### ISSUE TITLE
Enable/read user defined logged quantities from GSD files. 

### ISSUE THREAD

**Issue by lyrivera** [glotzerlab/garnett#133]
## Description

Enable/read user defined logged quantities from GSD files. 

## Proposed solution
Add a `log` attribute (dictionary) to gsd frame objects similar to the gsd package implementation.

See https://gsd.readthedocs.io/en/latest/schema-hoomd.html#logged-data for more details.

## Additional context
None

**Comment by bdice** [comment]
@lyrivera It's important to consider the scope we want for garnett. Currently, I think one of the core strengths of garnett is that it chooses a large subset of core features from the various trajectory formats HOOMD has supported over time. Log quantities are definitely a useful feature for the gsd format. However, adding gsd log data to garnett moves away from the "core" features of _particle attributes_ (e.g. position, mass, charge) and _type attributes_ (e.g. shapes) that garnett currently supports.<sup>1</sup> The "log" attribute is rather specific to gsd, and GTAR is the only other format I know would be capable of storing arbitrary data -- but it's quite awkward to do that and I do not know of any users who have stored arbitrary log-like data in GTAR files.

The scope that I believe is implied by this issue is that garnett aims to provide a relatively **"full" convenience API** for all supported file formats. _Alternatively,_ garnett could primarily exist for **converting** trajectory formats, focusing explicitly on fields with common representations in multiple file formats. Adding the log data field doesn't really fit into this second choice of project scope, in my opinion. Either way, it would be good to define the scope more clearly as the package continues to mature / stabilize.

If we choose to implement this (which puts garnett rather close to duplicating the full feature set of the standard gsd Python API), I think it's important to explain why one might use garnett over the standard gsd Python API at all. Below are the reasons I have in mind, though other reasons may exist:
- The API is primarily trajectory-first (instead of frame-first, which is how I would describe the gsd Python API)
- The API is designed to offer several conveniences to the user (e.g. shorter access to common properties like `frame.box` and `frame.positions`, a simple context manager `garnett.read` for reading trajectories)
- `garnett` includes explicit support for shape data (gsd just stores raw JSON)
- `garnett` offers convenient methods for accessing/manipulating entire trajectories in memory (when possible), making computations like [MSD](https://freud.readthedocs.io/en/stable/modules/msd.html#freud.msd.MSD) much easier to write

<sup>1</sup>In terms of file type support, garnett also ignores many other gsd fields such as bonds, angles, dihedral, impropers, constraints, special pairs, and possibly the timestep `configuration/step`.

**Comment by lyrivera** [comment]
> @lyrivera It's important to consider the scope we want for garnett. Currently, I think one of the core strengths of garnett is that it chooses a large subset of core features from the various trajectory formats HOOMD has supported over time. Log quantities are definitely a useful feature for the gsd format. However, adding gsd log data to garnett moves away from the "core" features of _particle attributes_ (e.g. position, mass, charge) and _type attributes_ (e.g. shapes) that garnett currently supports.1 The "log" attribute is rather specific to gsd, and GTAR is the only other format I know would be capable of storing arbitrary data -- but it's quite awkward to do that and I do not know of any users who have stored arbitrary log-like data in GTAR files.
> 
> The scope that I believe is implied by this issue is that garnett aims to provide a relatively **"full" convenience API** for all supported file formats. _Alternatively,_ garnett could primarily exist for **converting** trajectory formats, focusing explicitly on fields with common representations in multiple file formats. Adding the log data field doesn't really fit into this second choice of project scope, in my opinion. Either way, it would be good to define the scope more clearly as the package continues to mature / stabilize.
> 
> If we choose to implement this (which puts garnett rather close to duplicating the full feature set of the standard gsd Python API), I think it's important to explain why one might use garnett over the standard gsd Python API at all. Below are the reasons I have in mind, though other reasons may exist:
> 
> * The API is primarily trajectory-first (instead of frame-first, which is how I would describe the gsd Python API)
> * The API is designed to offer several conveniences to the user (e.g. shorter access to common properties like `frame.box` and `frame.positions`, a simple context manager `garnett.read` for reading trajectories)
> * `garnett` includes explicit support for shape data (gsd just stores raw JSON)
> * `garnett` offers convenient methods for accessing/manipulating entire trajectories in memory (when possible), making computations like [MSD](https://freud.readthedocs.io/en/stable/modules/msd.html#freud.msd.MSD) much easier to write
> 
> 1In terms of file type support, garnett also ignores many other gsd fields such as bonds, angles, dihedral, impropers, constraints, special pairs, and possibly the timestep `configuration/step`.

@bdice  Put that way it makes sense. Perhaps we should put this aside for now and until we discuss it further

**Comment by bdice** [comment]
@lyrivera If the feature benefits your research work, I think it's a fine idea to implement it. For example, if you need to extract shape info and log data. I just wanted to put some thoughts out there for consideration. 🤔💭

**Comment by lyrivera** [comment]
> @lyrivera If the feature benefits your research work, I think it's a fine idea to implement it. For example, if you need to extract shape info and log data. I just wanted to put some thoughts out there for consideration. 🤔💭

@bdice I agree with the point you made before, specially with all the flexibility that the user now has over loggable quantities. I will close this issue for now.
