### ISSUE TITLE
Drop python2 support

### ISSUE THREAD

**Issue by lyrivera** [glotzerlab/garnett#59]
Remove python2 support

**Comment by bdice** [comment]
@glotzerlab/garnett-maintainers I see that Python 2.7 tests failed in #80. The current CI testing code builds GSD and libgetar from source and tests against the latest version of each. GSD dropped support for Python 2 with v1.8.0. I recommend dropping Python 2 support in this package immediately after the v0.5 release.

For now, the CI could just run `pip install gsd libgetar` instead of building those two from source. That way, the latest compatible version (e.g. v1.7 for Python 2) will always be fetched. I don't think there are any significant downsides to that compared to the source builds, since GSD and libgetar are both pretty stable at this point.

**Comment by lyrivera** [comment]
> @glotzerlab/garnett-maintainers I see that Python 2.7 tests failed in #80. The current CI testing code builds GSD and libgetar from source and tests against the latest version of each. GSD dropped support for Python 2 with v1.8.0, which caused the errors in those tests. I recommend dropping Python 2 support in this package immediately after the v0.5 release.
> 
> For now, the CI could just run `pip install gsd libgetar` instead of building those two from source. That way, the latest compatible version (e.g. v1.7 for Python 2) will always be fetched. I don't think there are any significant downsides to that compared to the source builds, since GSD and libgetar are both pretty stable at this point.

I'll create a small PR for that
